deploy:
  provider: npm
  email: mr.tu@michaelqq.com
  api_key:
    secure: ISxVt+n1iFt0tTxQ4ptZZyd5sU/wVl3lmuqN39KD51+8s6QquQ7SH9/NEv7nVUHETY2wDAv2zTGRrIs5ewHZdIwlyn2zdPSlg1jto0GWIje3N7pMwRZetJxgZhP41cnIQCa4vdfbm1GrdhPSAqkn5iPYLzjRbSJLtaL01T2G1aoUUW9KBdTdHKzokQVgoMz0iBoBHb3CK5tkEqokNgXmBZG/lSBk6d7BKOXiWo6GjImrzm0jI0uUZQcbCbInY8jBXbO20EsQZfv1V2cDMm9yiY82Gij4ydWnlsP7iusfQ/xJCw/P7mzDIP8lNJJXkeFWZDxOk3u6UGQDExO/PNvJejpYGDpNwrx2r8nzufUyR8RnV4R6fNK733XuwGsAo6q897BRWWXFmJWjZHGhwuh3Ch2/8OF63zVNVF6j+iWlC3OWfOlcLn92uXKjHVQZCh0M+/hhwy/exoWdQGYKSAL39hZUJ3YMcRbPhbLhkuAbueFgzBARN8fxvTa7lLUO+gIxV5bh44CD1AiHUki6amYWm7vyJ9lkFsua+v/P1D1tt162YxjE7gMV3+MJ3J3JWH75m/Zs+cKchO1M4g9K4GNeWBm7xwLbo66b4tRrOEZkizqpDUSJoVRRC1xxSrKGZBCzE+7TMTPNdlcaJTSlSvpt9YK2bUKcznP7rcYUYMB5zhw=
  on:
    tags: true
    repo: MichaelQQ/dbfstream
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
