deploy:
  provider: npm
  email: mr.tu@michaelqq.com
  api_key:
    secure: hV0qydOJWAPs4COq77lb3r9mohauxwojic/KSS/v27DZeV7S0Q/xwFWsgr5RYKfaediod6tRmly7Gq3UgrxrMMUxbmUE2m9OePv+aefC12AdqhkntT0MAlWQd5UseY3xDOipEUSs+3hKaKlXn4J5egMG/M7GrrNOi4guH05PY7TlrBufBuuV57+4DkRs04eKW5RNB51zmlEzFFsO/VscwNRWtIJoIrPEsLAvTv96XMytetk/q7ekS4iCKmV7Hbc0dmKvcjY0CWEJNaa2AmMwIeK+tok9aPMbqsxN/QBqzFn3fih4Cd8skdHncxQ70UukfhMe+OtzIj9jscZ2gz51W81L4WIQq+6Wj7B1iwvByR7AcI7Cos+E9//T7q2+Ui/9fa87gukmp2EnSf7+t94wo3Ume6eQVEFrdXlrCwdnc5KjZd/41rgOXOPfobmM7WEfb1lDnyFtdG1rs7+LXmgVQV1XUXO+5WRlsjDRL5UKAb+uHY4HDmj7ZY4k8x4LM4UGOqOBO8CvVJcFvuQe/ly3i5wNmPkKTBskdWj3uUcd6FQpuBcucTfx+be1h63qSzNAiuNcN6ilueScjjrIWWiUGgzXPOtRUTjLBcC4tg3xBA9mAUzQlMV2PwWp8N3gikM76/TOwlgFJGK6KMQJ/QPNJItKIIeJZ+REgCYyZvsKtyE=
  on:
    tags: true
    repo: MichaelQQ/dbfstream
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
